workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

pipeline:
  supportvm:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: alpine
    commands:
    - apk add --no-cache docker
    - docker build -f docker/helper/Dockerfile -t cblomart/helper-vsphere-graphite docker/main
  deps:
    image: cblomart/helper-vsphere-graphite
    commands:
    - make deps
  checkups:
    image: cblomart/helper-vsphere-graphite
    commands:
    - make checks
  buildlin:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-amd64
  buildwin:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-windows-amd64
  buildosx:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-darwin-amd64
  buildarm:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-arm
