workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

# Build vsphere-graphite with drone.

pipeline:
  # perpare a helper image with necessary tooling deps included
  supportvm:
    name: Create Support Docker Image
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: docker
    commands:
    #- apk add --no-cache docker
    - cp Makefile docker/helper/
    - docker build -f docker/helper/Dockerfile -t cblomart/helper-vsphere-graphite docker/helper
  dependancies:
    name: Restore Dependances
    image: cblomart/helper-vsphere-graphite
    commands:
    - if [ -f /var/cache/drone/go.tgz ]; then tar -zxf /var/cache/drone/go.tgz -C /go/; else make godeps; fi
    - go generate ./...
  # do the checkups
  checkups:
    name: Golang Checkups
    image: cblomart/helper-vsphere-graphite
    commands:
    - make checks
  # buils
  buildlin:
    name: Build Linux AMD64
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-amd64
  buildwin:
    name: Build Windows AMD64
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-windows-amd64
    when:
      event: [ tag ]
  buildosx:
    name: Build OSX AMD64
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-darwin-amd64
    when:
      event: [ tag ]
  buildarm:
    name: Build Linux ARM
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-arm
    when:
      event: [ tag ]
  # push to docker
  pushlin:
    group: push
    name: Docker Push Linux AMD64
    image: cblomart/helper-vsphere-graphite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_username, docker_password ]
    commands:
    - make docker-linux-amd64
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - make push-linux-amd64