workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

pipeline:
  deps:
    image: golang:alpine
    commands:
    - make deps
  checkups:
    image: golang:alpine
    commands:
    - make checks
  buildlin:
    group: build
    image: golang:alpine
    commands:
    - apk add --no-cache upx
    - make build-linux-amd64
  buildwin:
    group: build
    image: golang:alpine
    commands:
    - make build-windows-amd64
  buildosx:
    group: build
    image: golang:alpine
    commands:
    - make build-darwin-amd64
  buildarm:
    group: build
    image: golang:alpine
    commands:
    - make build-linux-arm
