workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

pipeline:
  deps:
    image: golang:1.8
    commands:
    - go get
  checkups:
    image: golang:1.8
    commands:
    - go get honnef.co/go/tools/cmd/gosimple
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/gordonklaus/ineffassign
    - gosimple ./...
    - gofmt -s -d .
    - go vet ./...
    - golint ./...
    - ineffassign ./
  buildlin:
    group: build
    image: golang:1.8
    commands:
    - GOOS=linux GOARCH=amd64 go build -ldflags '-s -w' -a
  buildwin:
    group: build
    image: golang:1.8
    commands:
    - GOOS=windows GOARCH=amd64 go build -ldflags '-s -w' -a
  buildosx:
    group: build
    image: golang:1.8
    commands:
    - GOOS=darwin GOARCH=amd64 go build -ldflags '-s -w' -a
  buildarm:
    group: build
    image: golang:1.8
    commands:
    - GOOS=linux GOARCH=arm GOARM=5 go build -ldflags '-s -w' -a
