kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

steps:
  # check dependencies
  - dependancies:
    name: dependancies
    image: cblomart/gobasebuild
    commands:
    - go version
    - make godeps
    - go generate ./...
  # do the checkups
  - checkups:
    name: Golang Checkups
    image: cblomart/gobasebuild
    commands:
    - make checks
  # buils
  - buildlin:
    name: build linux amd64
    group: build
    image: cblomart/gobasebuild
    commands:
    - make build-linux-amd64
  - buildwin:
    name: build win amd64
    group: build
    image: cblomart/gobasebuild
    commands:
    - make build-windows-amd64
    when:
      event: [ tag ]
  - buildosx:
    name: build osx amd64
    group: build
    image: cblomart/gobasebuild
    commands:
    - make build-darwin-amd64
    when:
      event: [ tag ]
  - buildarm:
    name: build linux arm
    group: build
    image: cblomart/gobasebuild
    commands:
    - make build-linux-arm
    when:
      event: [ tag ]
  # push to docker
  - pushlin:
    group: push
    name: push linux amd64
    image: cblomart/gobasebuild
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    volumes:
    - name: docker
      path: /var/run/docker.sock
    commands:
    - make docker-linux-amd64
    - docker login -u cblomart -p $DOCKER_PASSWORD
    - make push-linux-amd64
  - pusharm:
    group: push
    name: push linux arm
    image: cblomart/gobasebuild
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    volumes:
    - name: docker
      path: /var/run/docker.sock
    commands:
    - make docker-linux-arm
    - docker login -u cblomart -p $DOCKER_PASSWORD
    - make push-linux-arm
    when:
      event: [ tag ]
  - packlin:
    name: pack linux amd64
    group: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-linux-amd64
    - cp /tmp/vsphere-graphite_*.tgz releases/
    when:
      event: [ tag ]
  - packwin:
    name: pack windows amd64
    group: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-windows-amd64
    - cp /tmp/vsphere-graphite_*.tgz releases/
    when:
      event: [ tag ]
  - packosx:
    name: pack osx amd64
    group: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-darwin-amd64
    - cp /tmp/vsphere-graphite_*.tgz releases/
    when:
      event: [ tag ]
  - packarm:
    name: pack linux arm
    group: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-linux-arm
    - cp /tmp/vsphere-graphite_*.tgz releases/
    when:
      event: [ tag ]
  - release:
    name: release
    image: plugins/github-release
    environment:
      GIHUB_SECRET:
        from_secret: github_secret
    files:
      - releases/*.tgz
    checksum:
      - sha256
    when:
      event: [ tag ]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
