workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

# Build vsphere-graphite with drone.

pipeline:
  # perpare a helper image with necessary tooling deps included
  supportvm:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: alpine
    commands:
    - apk add --no-cache docker
    - docker build -f docker/helper/Dockerfile -t cblomart/helper-vsphere-graphite docker/main
  # do the checkups
  dependancies:
    image: cblomart/helper-vsphere-graphite
    volumes:
      - /var/volumes/dronecache:/cache
    commands:
    - make deps
    - touch .ignorecache 
    - tar -zcf /tmp/vsphere-graphite-deps.tgz -C /go/ --exclude=*/vsphere-graphite/* ./
    - md5sum /tmp/vsphere-graphite-deps.tgz  | egrep -o '[A-Fa-f0-9]+' > /tmp/vsphere-graphite-deps.md5
    - if [ ! -f /cache/vsphere-graphite-deps.tgz ]; then cp -f /tmp/vsphere-graphite-deps.* /cache/; fi
    - if [ "$(cat /tmp/vsphere-graphite-deps.md5)" -ne "$(cat /cache/vsphere-graphite-deps.md5)" ]; then cp -f /tmp/vsphere-graphite-deps.* /cache/; fi
  checkups:
    image: cblomart/helper-vsphere-graphite
    commands:
    - make checks
  # buils
  buildlin:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-amd64
  buildwin:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-windows-amd64
    when:
      event: [ tag ]
  buildosx:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-darwin-amd64
    when:
      event: [ tag ]
  buildarm:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-arm
    when:
      event: [ tag ]
