workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

pipeline:
  deps:
    image: golang:1.8
    commands:
    - go get
  checkups:
    image: golang:1.8
    commands:
    - go get honnef.co/go/tools/cmd/gosimple
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/gordonklaus/ineffassign
    - gosimple ./...
    - gofmt -s -d .
    - go vet ./...
    - golint ./...
    - ineffassign ./
  coverage:
    image: golang:1.8
    environment:
    - COVERALLS_TOKEN=${COVERALLS_TOKEN}
    commands:
    - go get github.com/mattn/goveralls
    - goveralls -service=drone.io
  build:
    image: golang:1.8
    commands:
    - GOOS=${GOOS} GOARCH=${GOARCH} GOARM=5 go build -ldflags '-s -w' -a

matrix:
  include:
  - GOOS: linux
    GOARCH: amd64
  - GOOS: darwin
    GOARCH: amd64
  - GOOS: windows
    GOARCH: amd64
  - GOOS: linux
    GOARCH: arm
