workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

# Build vsphere-graphite with drone.

pipeline:
  # perpare a helper image with necessary tooling deps included
  supportvm:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: alpine
    commands:
    - apk add --no-cache docker
    - cp Makefile docker/helper/
    - docker build -f docker/helper/Dockerfile -t cblomart/helper-vsphere-graphite docker/main
  # do the checkups
  checkups:
    image: cblomart/helper-vsphere-graphite
    commands:
    - make checks
  # buils
  buildlin:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-amd64
  buildwin:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-windows-amd64
    when:
      event: [ tag ]
  buildosx:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-darwin-amd64
    when:
      event: [ tag ]
  buildarm:
    group: build
    image: cblomart/helper-vsphere-graphite
    commands:
    - make build-linux-arm
    when:
      event: [ tag ]
